let x = 1 + 1 * 2;
let y = (1 + 1) * 2;
let z = 1 + 1 * 2;
let a = 1 + (1 * 2) / 2;
let b = (1 + 1 * 2) / 2;
console.log('Value of x :' + x);
console.log('Value of y :' + y);
console.log('Value of z :' + z);
console.log('Value of a :' + a);
console.log('Value of b :' + b);
